\newcommand{\calC}{\mathcal{C}}
\newcommand{\calM}{\mathcal{M}}
\newcommand{\calL}{\mathcal{L}}
\newcommand{\calX}{\mathcal{X}}
\newcommand{\calW}{\mathcal{W}}

\newcommand{\proj}{\mathop{\mathrm{proj}}}
\newcommand{\prox}{\mathop{\mathrm{prox}}}
\newcommand{\id}{\mathop{\mathrm{id}}}

\newcommand{\RR}{\mathbb{R}}

\newcommand{\bfx}{\mathbf{x}}
\newcommand{\bfu}{\mathbf{u}}
\newcommand{\bmlam}{\boldsymbol{\lambda}}
\newcommand{\bmLam}{\boldsymbol{\Lambda}}

\newcommand{\subjectto}{\text{s.t.}\ }

\newcommand{\dim}{\mathrm{dim}}
\renewcommand{\epsilon}{\varepsilon}
\renewcommand{\phi}{\varphi}
