name: CI - Linux via CMake

on:
  push:
    branches:
      - main
      - devel
      - 'topic/**'
  pull_request:
  workflow_dispatch:
env:
  CCACHE_DIR: ~/.ccache
  CTEST_OUTPUT_ON_FAILURE: 1
  CTEST_PARALLEL_LEVEL: 4
  NJOBS: 8

defaults:
  run:
    shell: bash -leo pipefail {0} {0}
jobs:
  build-proxsuite-nlp:
    name: Build proxsuite-nlp
    runs-on: self-hosted
    steps:
    - name: Config for main
      if: github.ref == 'refs/heads/main'
      run: |
        echo "PROXSUITE_NLP_BRANCH=main" >> $GITHUB_ENV

    - name: Config for others
      if: github.ref != 'refs/heads/main'
      run: |
        echo "PROXSUITE_NLP_BRANCH=devel" >> $GITHUB_ENV

    - uses: actions/cache@v3
      with:
        key: ${{ runner.os }}
        path: ${{ env.CCACHE_DIR }}

    - uses: actions/checkout@v4
      with:
        ref: ${{ env.PROXSUITE_NLP_BRANCH }}
        fetch-depth: 0
        path: ./proxsuite-nlp
        submodules: recursive
        repository: Simple-Robotics/proxsuite-nlp

    - name: Install proxsuite-nlp
      run: |
        cd $GITHUB_WORKSPACE/proxsuite-nlp
        mkdir build && cd build

        cmake .. -DBUILD_DOCUMENTATION=OFF \
          -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX \
          -DCMAKE_BUILD_TYPE=Release
        make -j$NJOBS install
        python3 -c "import proxsuite_nlp"

  build:
    name: Build proxddp
    needs: build-proxsuite-nlp
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
      with:
        path: ./proxddp
        fetch-depth: 0
        submodules: recursive

    - name: Build and install proxddp
      run: |
        cd $GITHUB_WORKSPACE/proxddp
        mkdir build && cd build

        cmake .. -DBUILD_DOCUMENTATION=OFF \
          -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_CROCODDYL_COMPAT:BOOL=ON \
          -DBUILD_WITH_OPENMP_SUPPORT:BOOL=OFF
        make -j$NJOBS install

    - name: Run tests
      run: |
        cd $GITHUB_WORKSPACE/proxddp
        cd build && ctest

  cleanup:
    name: Cleanup
    needs: build
    runs-on: self-hosted
    if: always()
    steps:
    - run: |
        cd $GITHUB_WORKSPACE/proxddp
        cd build/ && make uninstall
        cd .. && rm -r build/
        cd $GITHUB_WORKSPACE/proxsuite-nlp
        cd build/ && make uninstall
        cd .. && rm -r build/
