name: CI - Linux via CMake

on: [push,pull_request]

jobs:
  call-proxnlp-linux-workflow:
    uses: Simple-Robotics/proxnlp/.github/workflows/linux.yml@devel

  proxddp:

    needs: call-proxnlp-linux-workflow
    runs-on: self-hosted

    env:
      CCACHE_DIR: /github/home/.ccache
      CMAKE_PREFIX_PATH: ~/custom_install

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Setup ccache
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}
        path: ${{ env.CCACHE_DIR }}

    - name: Set env variables
      run: |
        echo "PYTHONPATH=/builds/custom_install/lib/python3/dist-packages/" >> $GITHUB_ENV
        echo "CTEST_OUTPUT_ON_FAILURE=1" >> $GITHUB_ENV
        echo "CTEST_PARALLEL_LEVEL=4" >> $GITHUB_ENV

    - name: Build proxddp and test
      run: |
        cd $GITHUB_WORKSPACE
        mkdir build
        cd build
        cmake .. -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_INSTALL_PREFIX=~/custom_install -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=$(which python3) -DINSTALL_DOCUMENTATION:BOOL=OFF -DGENERATE_PYTHON_STUBS:BOOL=OFF -DBUILD_CROCODDYL_COMPAT:BOOL=ON -DBUILD_WITH_OPENMP_SUPPORT:BOOL=OFF
        make install
        make test

    # - name: Uninstall project
    #   run: |
    #     cd build
    #     sudo make uninstall
